
"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""


def top(list):
    return list[-1] + list[-2]

fibo = [1,2]

while top(fibo) < 4000000:
    fibo.append(top(fibo))

print(fibo)